/* tslint:disable */
/* eslint-disable */
// @ts-ignore
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
/// <reference path="./thrift/index.d.ts" />
import * as thrift from "./thrift/thrift.js";
import * as __ROOT_NAMESPACE__ from "./index.ts";
export interface Icall_globalArgs {
    hub_name?: string;
    message?: __ROOT_NAMESPACE__.msg;
}
export class call_global {
    public hub_name?: string;
    public message?: __ROOT_NAMESPACE__.msg;
    constructor(args?: Icall_globalArgs) {
        if (args != null && args.hub_name != null) {
            this.hub_name = args.hub_name;
        }
        if (args != null && args.message != null) {
            this.message = args.message;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("call_global");
        if (this.hub_name != null) {
            output.writeFieldBegin("hub_name", thrift.Type.STRING, 1);
            output.writeString(this.hub_name);
            output.writeFieldEnd();
        }
        if (this.message != null) {
            output.writeFieldBegin("message", thrift.Type.STRUCT, 2);
            this.message.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): call_global {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.hub_name = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Type.STRUCT) {
                        const value_2: __ROOT_NAMESPACE__.msg = __ROOT_NAMESPACE__.msg.read(input);
                        _args.message = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new call_global(_args);
    }
}
