/* tslint:disable */
/* eslint-disable */
// @ts-ignore
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
/// <reference path="./thrift/index.d.ts" />
import * as thrift from "./thrift/thrift.js";
import * as __ROOT_NAMESPACE__ from "./index.ts";
export interface Ihub_call_client_globalArgs {
    message?: __ROOT_NAMESPACE__.msg;
}
export class hub_call_client_global {
    public message?: __ROOT_NAMESPACE__.msg;
    constructor(args?: Ihub_call_client_globalArgs) {
        if (args != null && args.message != null) {
            this.message = args.message;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("hub_call_client_global");
        if (this.message != null) {
            output.writeFieldBegin("message", thrift.Type.STRUCT, 1);
            this.message.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): hub_call_client_global {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Type.STRUCT) {
                        const value_1: __ROOT_NAMESPACE__.msg = __ROOT_NAMESPACE__.msg.read(input);
                        _args.message = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new hub_call_client_global(_args);
    }
}
