/* tslint:disable */
/* eslint-disable */
// @ts-ignore
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
/// <reference path="./thrift/index.d.ts" />
import * as thrift from "./thrift/thrift.js";
export interface Itransfer_completeArgs {
}
export class transfer_complete {
    constructor() {
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("transfer_complete");
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): transfer_complete {
        input.readStructBegin();
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new transfer_complete();
    }
}
