syntax = "proto3"; 

enum EPlatform {
  EPlatformNone = 0;

  EPlatformWX = 1;
  EPlatformTap = 2;
  EPlatformDy = 3;
}

message LoginRequest {
  string code = 1;
  EPlatform Platform = 2;
}

message LoginResponse {
  PlayerDataInfo info = 1;
}

enum EAttribute {
  EAttributeNone = 0;

  EStrength = 1;          // 力量
  EAgility = 2;           // 敏捷
  EIntelligence = 3;      // 法术/智力

  HP = 4;
  MP = 5;

  EPhysicalAttack = 6;    // 物理攻击
  EPhysicalDefense = 7;   // 物理防御
  EMagicAttack = 8;       // 法术攻击
  EMagicDefense = 9;      // 法术防御

  ESpeed = 10;            // 速度
}

enum ERarity {
  ERarityNone = 0;

  ECommon = 1;     // 普通
  ERare = 2;       // 稀有
  EEpic = 3;       // 史诗
  ELegendary = 4;  // 传说
}

message CultivationSkill {
  repeated uint32 ActiveSkills = 1;
  repeated uint32 PassiveSkills = 2;
}

message CultivationInfo {
  string CultivationID = 1;
  uint32 CultivationTableID = 2;
  ERarity Rarity = 3;
  uint64 XP = 4;
  string Description = 5;
  CultivationSkill Skills = 6;
  map<string, uint32> Attributes = 7;
}

message ItemInfo {
  uint32 ID = 1;
  uint32 count = 2;
}

message BBInfo {
  string BBID = 1;
  uint32 BBTableID = 2;
  ERarity Rarity = 3;
  float Growth = 4;
  repeated uint32 Skills = 5;
  map<string, uint32> Attributes = 6;
}

message Bag {
  repeated ItemInfo items = 1;
  repeated BBInfo BBs = 2;
}

enum EEquip {
  EEquipNone = 0;

  EHelmet = 1; //头
  EChest = 2;  //上衣
  ELegs = 3;   //裤子
  EFeet = 4;   //鞋子
  EWeapon = 5; //武器
}

message PlayerDataInfo {
  CultivationInfo CurrCultivation = 1;
  repeated CultivationInfo CurrCultivationList = 2;
  Bag BagInfo = 3;
  map<string, uint32> EquipInfo = 4;
  map<string, uint32> Attributes = 5;
  repeated BBInfo BattleBBs = 6;
}

message LearnOrGearCultivationRequest {
  uint32 CultivationTableID = 1;
}

message LearnOrGearCultivationResponse {
  CultivationInfo info = 1;
}

message CreateCultivationRequest {
  string CultivationID0 = 1;
  string CultivationID1 = 2;
  string Description = 3;
}

message CreateCultivationResponse {
  string CultivationID = 1;
  uint32 CultivationTableID = 2;
  map<string, uint32> Attributes = 3;
  bool IsNeedSelect = 4;
  repeated CultivationSkill Skills = 5;
}

message SelectCultivationRequest { 
  string CultivationID = 1;
  CultivationSkill Skills = 2;
}

message SelectCultivationResponse {
  CultivationInfo info = 1;
}

message FusionBBRequest {
  string BB0 = 1;
  string BB1 = 2;
}

message FusionBBRespone {
  BBInfo NewBB = 1;
}