// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.34.0
// source: message.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export enum EPlatform {
  EPlatformNone = 0,
  EPlatformWX = 1,
  EPlatformTap = 2,
  EPlatformDy = 3,
  UNRECOGNIZED = -1,
}

export function ePlatformFromJSON(object: any): EPlatform {
  switch (object) {
    case 0:
    case "EPlatformNone":
      return EPlatform.EPlatformNone;
    case 1:
    case "EPlatformWX":
      return EPlatform.EPlatformWX;
    case 2:
    case "EPlatformTap":
      return EPlatform.EPlatformTap;
    case 3:
    case "EPlatformDy":
      return EPlatform.EPlatformDy;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EPlatform.UNRECOGNIZED;
  }
}

export function ePlatformToJSON(object: EPlatform): string {
  switch (object) {
    case EPlatform.EPlatformNone:
      return "EPlatformNone";
    case EPlatform.EPlatformWX:
      return "EPlatformWX";
    case EPlatform.EPlatformTap:
      return "EPlatformTap";
    case EPlatform.EPlatformDy:
      return "EPlatformDy";
    case EPlatform.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum EAttribute {
  EAttributeNone = 0,
  /** EStrength - 力量 */
  EStrength = 1,
  /** EAgility - 敏捷 */
  EAgility = 2,
  /** EIntelligence - 法术/智力 */
  EIntelligence = 3,
  HP = 4,
  MP = 5,
  /** EPhysicalAttack - 物理攻击 */
  EPhysicalAttack = 6,
  /** EPhysicalDefense - 物理防御 */
  EPhysicalDefense = 7,
  /** EMagicAttack - 法术攻击 */
  EMagicAttack = 8,
  /** EMagicDefense - 法术防御 */
  EMagicDefense = 9,
  /** ESpeed - 速度 */
  ESpeed = 10,
  UNRECOGNIZED = -1,
}

export function eAttributeFromJSON(object: any): EAttribute {
  switch (object) {
    case 0:
    case "EAttributeNone":
      return EAttribute.EAttributeNone;
    case 1:
    case "EStrength":
      return EAttribute.EStrength;
    case 2:
    case "EAgility":
      return EAttribute.EAgility;
    case 3:
    case "EIntelligence":
      return EAttribute.EIntelligence;
    case 4:
    case "HP":
      return EAttribute.HP;
    case 5:
    case "MP":
      return EAttribute.MP;
    case 6:
    case "EPhysicalAttack":
      return EAttribute.EPhysicalAttack;
    case 7:
    case "EPhysicalDefense":
      return EAttribute.EPhysicalDefense;
    case 8:
    case "EMagicAttack":
      return EAttribute.EMagicAttack;
    case 9:
    case "EMagicDefense":
      return EAttribute.EMagicDefense;
    case 10:
    case "ESpeed":
      return EAttribute.ESpeed;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EAttribute.UNRECOGNIZED;
  }
}

export function eAttributeToJSON(object: EAttribute): string {
  switch (object) {
    case EAttribute.EAttributeNone:
      return "EAttributeNone";
    case EAttribute.EStrength:
      return "EStrength";
    case EAttribute.EAgility:
      return "EAgility";
    case EAttribute.EIntelligence:
      return "EIntelligence";
    case EAttribute.HP:
      return "HP";
    case EAttribute.MP:
      return "MP";
    case EAttribute.EPhysicalAttack:
      return "EPhysicalAttack";
    case EAttribute.EPhysicalDefense:
      return "EPhysicalDefense";
    case EAttribute.EMagicAttack:
      return "EMagicAttack";
    case EAttribute.EMagicDefense:
      return "EMagicDefense";
    case EAttribute.ESpeed:
      return "ESpeed";
    case EAttribute.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ERarity {
  ERarityNone = 0,
  /** ECommon - 普通 */
  ECommon = 1,
  /** ERare - 稀有 */
  ERare = 2,
  /** EEpic - 史诗 */
  EEpic = 3,
  /** ELegendary - 传说 */
  ELegendary = 4,
  UNRECOGNIZED = -1,
}

export function eRarityFromJSON(object: any): ERarity {
  switch (object) {
    case 0:
    case "ERarityNone":
      return ERarity.ERarityNone;
    case 1:
    case "ECommon":
      return ERarity.ECommon;
    case 2:
    case "ERare":
      return ERarity.ERare;
    case 3:
    case "EEpic":
      return ERarity.EEpic;
    case 4:
    case "ELegendary":
      return ERarity.ELegendary;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ERarity.UNRECOGNIZED;
  }
}

export function eRarityToJSON(object: ERarity): string {
  switch (object) {
    case ERarity.ERarityNone:
      return "ERarityNone";
    case ERarity.ECommon:
      return "ECommon";
    case ERarity.ERare:
      return "ERare";
    case ERarity.EEpic:
      return "EEpic";
    case ERarity.ELegendary:
      return "ELegendary";
    case ERarity.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum EEquip {
  EEquipNone = 0,
  /** EHelmet - 头 */
  EHelmet = 1,
  /** EChest - 上衣 */
  EChest = 2,
  /** ELegs - 裤子 */
  ELegs = 3,
  /** EFeet - 鞋子 */
  EFeet = 4,
  /** EWeapon - 武器 */
  EWeapon = 5,
  UNRECOGNIZED = -1,
}

export function eEquipFromJSON(object: any): EEquip {
  switch (object) {
    case 0:
    case "EEquipNone":
      return EEquip.EEquipNone;
    case 1:
    case "EHelmet":
      return EEquip.EHelmet;
    case 2:
    case "EChest":
      return EEquip.EChest;
    case 3:
    case "ELegs":
      return EEquip.ELegs;
    case 4:
    case "EFeet":
      return EEquip.EFeet;
    case 5:
    case "EWeapon":
      return EEquip.EWeapon;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EEquip.UNRECOGNIZED;
  }
}

export function eEquipToJSON(object: EEquip): string {
  switch (object) {
    case EEquip.EEquipNone:
      return "EEquipNone";
    case EEquip.EHelmet:
      return "EHelmet";
    case EEquip.EChest:
      return "EChest";
    case EEquip.ELegs:
      return "ELegs";
    case EEquip.EFeet:
      return "EFeet";
    case EEquip.EWeapon:
      return "EWeapon";
    case EEquip.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface LoginRequest {
  code: string;
  Platform: EPlatform;
}

export interface LoginResponse {
  info: PlayerDataInfo | undefined;
}

export interface CultivationSkill {
  ActiveSkills: number[];
  PassiveSkills: number[];
}

export interface CultivationInfo {
  CultivationID: string;
  CultivationTableID: number;
  XP: number;
  Skills: CultivationSkill | undefined;
  Attributes: { [key: string]: number };
  Description: string;
  Rarity: ERarity;
}

export interface CultivationInfo_AttributesEntry {
  key: string;
  value: number;
}

export interface ItemInfo {
  ID: number;
  count: number;
}

export interface BBInfo {
  BBID: string;
  BBTableID: number;
  Rarity: ERarity;
  Growth: number;
  Skills: CultivationSkill | undefined;
  Attributes: { [key: string]: number };
}

export interface BBInfo_AttributesEntry {
  key: string;
  value: number;
}

export interface Bag {
  items: ItemInfo[];
  BBs: BBInfo[];
}

export interface PlayerDataInfo {
  CurrCultivation: CultivationInfo | undefined;
  CurrCultivationList: CultivationInfo[];
  BagInfo: Bag | undefined;
  EquipInfo: { [key: string]: number };
  Attributes: { [key: string]: number };
  BattleBBs: BBInfo[];
}

export interface PlayerDataInfo_EquipInfoEntry {
  key: string;
  value: number;
}

export interface PlayerDataInfo_AttributesEntry {
  key: string;
  value: number;
}

export interface LearnOrGearCultivationRequest {
  CultivationTableID: number;
}

export interface LearnOrGearCultivationResponse {
  info: CultivationInfo | undefined;
}

export interface CreateCultivationRequest {
  CultivationID0: string;
  CultivationID1: string;
  Description: string;
}

export interface CreateCultivationResponse {
  CultivationID: string;
  CultivationTableID: number;
  Attributes: { [key: string]: number };
  IsNeedSelect: boolean;
  Skills: CultivationSkill[];
}

export interface CreateCultivationResponse_AttributesEntry {
  key: string;
  value: number;
}

export interface SelectCultivationRequest {
  CultivationID: string;
  Skills: CultivationSkill | undefined;
}

export interface SelectCultivationResponse {
  info: CultivationInfo | undefined;
}

export interface FusionBBRequest {
  BB0: string;
  BB1: string;
}

export interface FusionBBRespone {
  NewBB: BBInfo | undefined;
}

function createBaseLoginRequest(): LoginRequest {
  return { code: "", Platform: 0 };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.Platform !== 0) {
      writer.uint32(16).int32(message.Platform);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.Platform = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      Platform: isSet(object.Platform) ? ePlatformFromJSON(object.Platform) : 0,
    };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.Platform !== 0) {
      obj.Platform = ePlatformToJSON(message.Platform);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.code = object.code ?? "";
    message.Platform = object.Platform ?? 0;
    return message;
  },
};

function createBaseLoginResponse(): LoginResponse {
  return { info: undefined };
}

export const LoginResponse: MessageFns<LoginResponse> = {
  encode(message: LoginResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      PlayerDataInfo.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = PlayerDataInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResponse {
    return { info: isSet(object.info) ? PlayerDataInfo.fromJSON(object.info) : undefined };
  },

  toJSON(message: LoginResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = PlayerDataInfo.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResponse>, I>>(base?: I): LoginResponse {
    return LoginResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResponse>, I>>(object: I): LoginResponse {
    const message = createBaseLoginResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? PlayerDataInfo.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseCultivationSkill(): CultivationSkill {
  return { ActiveSkills: [], PassiveSkills: [] };
}

export const CultivationSkill: MessageFns<CultivationSkill> = {
  encode(message: CultivationSkill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.ActiveSkills) {
      writer.uint32(v);
    }
    writer.join();
    writer.uint32(18).fork();
    for (const v of message.PassiveSkills) {
      writer.uint32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CultivationSkill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCultivationSkill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.ActiveSkills.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ActiveSkills.push(reader.uint32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag === 16) {
            message.PassiveSkills.push(reader.uint32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.PassiveSkills.push(reader.uint32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CultivationSkill {
    return {
      ActiveSkills: globalThis.Array.isArray(object?.ActiveSkills)
        ? object.ActiveSkills.map((e: any) => globalThis.Number(e))
        : [],
      PassiveSkills: globalThis.Array.isArray(object?.PassiveSkills)
        ? object.PassiveSkills.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: CultivationSkill): unknown {
    const obj: any = {};
    if (message.ActiveSkills?.length) {
      obj.ActiveSkills = message.ActiveSkills.map((e) => Math.round(e));
    }
    if (message.PassiveSkills?.length) {
      obj.PassiveSkills = message.PassiveSkills.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CultivationSkill>, I>>(base?: I): CultivationSkill {
    return CultivationSkill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CultivationSkill>, I>>(object: I): CultivationSkill {
    const message = createBaseCultivationSkill();
    message.ActiveSkills = object.ActiveSkills?.map((e) => e) || [];
    message.PassiveSkills = object.PassiveSkills?.map((e) => e) || [];
    return message;
  },
};

function createBaseCultivationInfo(): CultivationInfo {
  return {
    CultivationID: "",
    CultivationTableID: 0,
    XP: 0,
    Skills: undefined,
    Attributes: {},
    Description: "",
    Rarity: 0,
  };
}

export const CultivationInfo: MessageFns<CultivationInfo> = {
  encode(message: CultivationInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.CultivationID !== "") {
      writer.uint32(10).string(message.CultivationID);
    }
    if (message.CultivationTableID !== 0) {
      writer.uint32(16).uint32(message.CultivationTableID);
    }
    if (message.XP !== 0) {
      writer.uint32(24).uint64(message.XP);
    }
    if (message.Skills !== undefined) {
      CultivationSkill.encode(message.Skills, writer.uint32(34).fork()).join();
    }
    globalThis.Object.entries(message.Attributes).forEach(([key, value]: [string, number]) => {
      CultivationInfo_AttributesEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    if (message.Description !== "") {
      writer.uint32(50).string(message.Description);
    }
    if (message.Rarity !== 0) {
      writer.uint32(56).int32(message.Rarity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CultivationInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCultivationInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.CultivationID = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.CultivationTableID = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.XP = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.Skills = CultivationSkill.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = CultivationInfo_AttributesEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.Attributes[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.Description = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.Rarity = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CultivationInfo {
    return {
      CultivationID: isSet(object.CultivationID) ? globalThis.String(object.CultivationID) : "",
      CultivationTableID: isSet(object.CultivationTableID) ? globalThis.Number(object.CultivationTableID) : 0,
      XP: isSet(object.XP) ? globalThis.Number(object.XP) : 0,
      Skills: isSet(object.Skills) ? CultivationSkill.fromJSON(object.Skills) : undefined,
      Attributes: isObject(object.Attributes)
        ? (globalThis.Object.entries(object.Attributes) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      Description: isSet(object.Description) ? globalThis.String(object.Description) : "",
      Rarity: isSet(object.Rarity) ? eRarityFromJSON(object.Rarity) : 0,
    };
  },

  toJSON(message: CultivationInfo): unknown {
    const obj: any = {};
    if (message.CultivationID !== "") {
      obj.CultivationID = message.CultivationID;
    }
    if (message.CultivationTableID !== 0) {
      obj.CultivationTableID = Math.round(message.CultivationTableID);
    }
    if (message.XP !== 0) {
      obj.XP = Math.round(message.XP);
    }
    if (message.Skills !== undefined) {
      obj.Skills = CultivationSkill.toJSON(message.Skills);
    }
    if (message.Attributes) {
      const entries = globalThis.Object.entries(message.Attributes) as [string, number][];
      if (entries.length > 0) {
        obj.Attributes = {};
        entries.forEach(([k, v]) => {
          obj.Attributes[k] = Math.round(v);
        });
      }
    }
    if (message.Description !== "") {
      obj.Description = message.Description;
    }
    if (message.Rarity !== 0) {
      obj.Rarity = eRarityToJSON(message.Rarity);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CultivationInfo>, I>>(base?: I): CultivationInfo {
    return CultivationInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CultivationInfo>, I>>(object: I): CultivationInfo {
    const message = createBaseCultivationInfo();
    message.CultivationID = object.CultivationID ?? "";
    message.CultivationTableID = object.CultivationTableID ?? 0;
    message.XP = object.XP ?? 0;
    message.Skills = (object.Skills !== undefined && object.Skills !== null)
      ? CultivationSkill.fromPartial(object.Skills)
      : undefined;
    message.Attributes = (globalThis.Object.entries(object.Attributes ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.Description = object.Description ?? "";
    message.Rarity = object.Rarity ?? 0;
    return message;
  },
};

function createBaseCultivationInfo_AttributesEntry(): CultivationInfo_AttributesEntry {
  return { key: "", value: 0 };
}

export const CultivationInfo_AttributesEntry: MessageFns<CultivationInfo_AttributesEntry> = {
  encode(message: CultivationInfo_AttributesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CultivationInfo_AttributesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCultivationInfo_AttributesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CultivationInfo_AttributesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: CultivationInfo_AttributesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CultivationInfo_AttributesEntry>, I>>(base?: I): CultivationInfo_AttributesEntry {
    return CultivationInfo_AttributesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CultivationInfo_AttributesEntry>, I>>(
    object: I,
  ): CultivationInfo_AttributesEntry {
    const message = createBaseCultivationInfo_AttributesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseItemInfo(): ItemInfo {
  return { ID: 0, count: 0 };
}

export const ItemInfo: MessageFns<ItemInfo> = {
  encode(message: ItemInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ID !== 0) {
      writer.uint32(8).uint32(message.ID);
    }
    if (message.count !== 0) {
      writer.uint32(16).uint32(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ItemInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItemInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ID = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ItemInfo {
    return {
      ID: isSet(object.ID) ? globalThis.Number(object.ID) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
    };
  },

  toJSON(message: ItemInfo): unknown {
    const obj: any = {};
    if (message.ID !== 0) {
      obj.ID = Math.round(message.ID);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ItemInfo>, I>>(base?: I): ItemInfo {
    return ItemInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ItemInfo>, I>>(object: I): ItemInfo {
    const message = createBaseItemInfo();
    message.ID = object.ID ?? 0;
    message.count = object.count ?? 0;
    return message;
  },
};

function createBaseBBInfo(): BBInfo {
  return { BBID: "", BBTableID: 0, Rarity: 0, Growth: 0, Skills: undefined, Attributes: {} };
}

export const BBInfo: MessageFns<BBInfo> = {
  encode(message: BBInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.BBID !== "") {
      writer.uint32(10).string(message.BBID);
    }
    if (message.BBTableID !== 0) {
      writer.uint32(16).uint32(message.BBTableID);
    }
    if (message.Rarity !== 0) {
      writer.uint32(24).int32(message.Rarity);
    }
    if (message.Growth !== 0) {
      writer.uint32(37).float(message.Growth);
    }
    if (message.Skills !== undefined) {
      CultivationSkill.encode(message.Skills, writer.uint32(42).fork()).join();
    }
    globalThis.Object.entries(message.Attributes).forEach(([key, value]: [string, number]) => {
      BBInfo_AttributesEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BBInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBBInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.BBID = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.BBTableID = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.Rarity = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.Growth = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.Skills = CultivationSkill.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = BBInfo_AttributesEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.Attributes[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BBInfo {
    return {
      BBID: isSet(object.BBID) ? globalThis.String(object.BBID) : "",
      BBTableID: isSet(object.BBTableID) ? globalThis.Number(object.BBTableID) : 0,
      Rarity: isSet(object.Rarity) ? eRarityFromJSON(object.Rarity) : 0,
      Growth: isSet(object.Growth) ? globalThis.Number(object.Growth) : 0,
      Skills: isSet(object.Skills) ? CultivationSkill.fromJSON(object.Skills) : undefined,
      Attributes: isObject(object.Attributes)
        ? (globalThis.Object.entries(object.Attributes) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: BBInfo): unknown {
    const obj: any = {};
    if (message.BBID !== "") {
      obj.BBID = message.BBID;
    }
    if (message.BBTableID !== 0) {
      obj.BBTableID = Math.round(message.BBTableID);
    }
    if (message.Rarity !== 0) {
      obj.Rarity = eRarityToJSON(message.Rarity);
    }
    if (message.Growth !== 0) {
      obj.Growth = message.Growth;
    }
    if (message.Skills !== undefined) {
      obj.Skills = CultivationSkill.toJSON(message.Skills);
    }
    if (message.Attributes) {
      const entries = globalThis.Object.entries(message.Attributes) as [string, number][];
      if (entries.length > 0) {
        obj.Attributes = {};
        entries.forEach(([k, v]) => {
          obj.Attributes[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BBInfo>, I>>(base?: I): BBInfo {
    return BBInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BBInfo>, I>>(object: I): BBInfo {
    const message = createBaseBBInfo();
    message.BBID = object.BBID ?? "";
    message.BBTableID = object.BBTableID ?? 0;
    message.Rarity = object.Rarity ?? 0;
    message.Growth = object.Growth ?? 0;
    message.Skills = (object.Skills !== undefined && object.Skills !== null)
      ? CultivationSkill.fromPartial(object.Skills)
      : undefined;
    message.Attributes = (globalThis.Object.entries(object.Attributes ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseBBInfo_AttributesEntry(): BBInfo_AttributesEntry {
  return { key: "", value: 0 };
}

export const BBInfo_AttributesEntry: MessageFns<BBInfo_AttributesEntry> = {
  encode(message: BBInfo_AttributesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BBInfo_AttributesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBBInfo_AttributesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BBInfo_AttributesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: BBInfo_AttributesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BBInfo_AttributesEntry>, I>>(base?: I): BBInfo_AttributesEntry {
    return BBInfo_AttributesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BBInfo_AttributesEntry>, I>>(object: I): BBInfo_AttributesEntry {
    const message = createBaseBBInfo_AttributesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseBag(): Bag {
  return { items: [], BBs: [] };
}

export const Bag: MessageFns<Bag> = {
  encode(message: Bag, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      ItemInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.BBs) {
      BBInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Bag {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBag();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(ItemInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.BBs.push(BBInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Bag {
    return {
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => ItemInfo.fromJSON(e)) : [],
      BBs: globalThis.Array.isArray(object?.BBs) ? object.BBs.map((e: any) => BBInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: Bag): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => ItemInfo.toJSON(e));
    }
    if (message.BBs?.length) {
      obj.BBs = message.BBs.map((e) => BBInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Bag>, I>>(base?: I): Bag {
    return Bag.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Bag>, I>>(object: I): Bag {
    const message = createBaseBag();
    message.items = object.items?.map((e) => ItemInfo.fromPartial(e)) || [];
    message.BBs = object.BBs?.map((e) => BBInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBasePlayerDataInfo(): PlayerDataInfo {
  return {
    CurrCultivation: undefined,
    CurrCultivationList: [],
    BagInfo: undefined,
    EquipInfo: {},
    Attributes: {},
    BattleBBs: [],
  };
}

export const PlayerDataInfo: MessageFns<PlayerDataInfo> = {
  encode(message: PlayerDataInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.CurrCultivation !== undefined) {
      CultivationInfo.encode(message.CurrCultivation, writer.uint32(10).fork()).join();
    }
    for (const v of message.CurrCultivationList) {
      CultivationInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.BagInfo !== undefined) {
      Bag.encode(message.BagInfo, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.EquipInfo).forEach(([key, value]: [string, number]) => {
      PlayerDataInfo_EquipInfoEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    globalThis.Object.entries(message.Attributes).forEach(([key, value]: [string, number]) => {
      PlayerDataInfo_AttributesEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    for (const v of message.BattleBBs) {
      BBInfo.encode(v!, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerDataInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerDataInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.CurrCultivation = CultivationInfo.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.CurrCultivationList.push(CultivationInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.BagInfo = Bag.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = PlayerDataInfo_EquipInfoEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.EquipInfo[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = PlayerDataInfo_AttributesEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.Attributes[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.BattleBBs.push(BBInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerDataInfo {
    return {
      CurrCultivation: isSet(object.CurrCultivation) ? CultivationInfo.fromJSON(object.CurrCultivation) : undefined,
      CurrCultivationList: globalThis.Array.isArray(object?.CurrCultivationList)
        ? object.CurrCultivationList.map((e: any) => CultivationInfo.fromJSON(e))
        : [],
      BagInfo: isSet(object.BagInfo) ? Bag.fromJSON(object.BagInfo) : undefined,
      EquipInfo: isObject(object.EquipInfo)
        ? (globalThis.Object.entries(object.EquipInfo) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      Attributes: isObject(object.Attributes)
        ? (globalThis.Object.entries(object.Attributes) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      BattleBBs: globalThis.Array.isArray(object?.BattleBBs)
        ? object.BattleBBs.map((e: any) => BBInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PlayerDataInfo): unknown {
    const obj: any = {};
    if (message.CurrCultivation !== undefined) {
      obj.CurrCultivation = CultivationInfo.toJSON(message.CurrCultivation);
    }
    if (message.CurrCultivationList?.length) {
      obj.CurrCultivationList = message.CurrCultivationList.map((e) => CultivationInfo.toJSON(e));
    }
    if (message.BagInfo !== undefined) {
      obj.BagInfo = Bag.toJSON(message.BagInfo);
    }
    if (message.EquipInfo) {
      const entries = globalThis.Object.entries(message.EquipInfo) as [string, number][];
      if (entries.length > 0) {
        obj.EquipInfo = {};
        entries.forEach(([k, v]) => {
          obj.EquipInfo[k] = Math.round(v);
        });
      }
    }
    if (message.Attributes) {
      const entries = globalThis.Object.entries(message.Attributes) as [string, number][];
      if (entries.length > 0) {
        obj.Attributes = {};
        entries.forEach(([k, v]) => {
          obj.Attributes[k] = Math.round(v);
        });
      }
    }
    if (message.BattleBBs?.length) {
      obj.BattleBBs = message.BattleBBs.map((e) => BBInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerDataInfo>, I>>(base?: I): PlayerDataInfo {
    return PlayerDataInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerDataInfo>, I>>(object: I): PlayerDataInfo {
    const message = createBasePlayerDataInfo();
    message.CurrCultivation = (object.CurrCultivation !== undefined && object.CurrCultivation !== null)
      ? CultivationInfo.fromPartial(object.CurrCultivation)
      : undefined;
    message.CurrCultivationList = object.CurrCultivationList?.map((e) => CultivationInfo.fromPartial(e)) || [];
    message.BagInfo = (object.BagInfo !== undefined && object.BagInfo !== null)
      ? Bag.fromPartial(object.BagInfo)
      : undefined;
    message.EquipInfo = (globalThis.Object.entries(object.EquipInfo ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.Attributes = (globalThis.Object.entries(object.Attributes ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.BattleBBs = object.BattleBBs?.map((e) => BBInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBasePlayerDataInfo_EquipInfoEntry(): PlayerDataInfo_EquipInfoEntry {
  return { key: "", value: 0 };
}

export const PlayerDataInfo_EquipInfoEntry: MessageFns<PlayerDataInfo_EquipInfoEntry> = {
  encode(message: PlayerDataInfo_EquipInfoEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerDataInfo_EquipInfoEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerDataInfo_EquipInfoEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerDataInfo_EquipInfoEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: PlayerDataInfo_EquipInfoEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerDataInfo_EquipInfoEntry>, I>>(base?: I): PlayerDataInfo_EquipInfoEntry {
    return PlayerDataInfo_EquipInfoEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerDataInfo_EquipInfoEntry>, I>>(
    object: I,
  ): PlayerDataInfo_EquipInfoEntry {
    const message = createBasePlayerDataInfo_EquipInfoEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBasePlayerDataInfo_AttributesEntry(): PlayerDataInfo_AttributesEntry {
  return { key: "", value: 0 };
}

export const PlayerDataInfo_AttributesEntry: MessageFns<PlayerDataInfo_AttributesEntry> = {
  encode(message: PlayerDataInfo_AttributesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerDataInfo_AttributesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerDataInfo_AttributesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerDataInfo_AttributesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: PlayerDataInfo_AttributesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerDataInfo_AttributesEntry>, I>>(base?: I): PlayerDataInfo_AttributesEntry {
    return PlayerDataInfo_AttributesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerDataInfo_AttributesEntry>, I>>(
    object: I,
  ): PlayerDataInfo_AttributesEntry {
    const message = createBasePlayerDataInfo_AttributesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseLearnOrGearCultivationRequest(): LearnOrGearCultivationRequest {
  return { CultivationTableID: 0 };
}

export const LearnOrGearCultivationRequest: MessageFns<LearnOrGearCultivationRequest> = {
  encode(message: LearnOrGearCultivationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.CultivationTableID !== 0) {
      writer.uint32(8).uint32(message.CultivationTableID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LearnOrGearCultivationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLearnOrGearCultivationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.CultivationTableID = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LearnOrGearCultivationRequest {
    return { CultivationTableID: isSet(object.CultivationTableID) ? globalThis.Number(object.CultivationTableID) : 0 };
  },

  toJSON(message: LearnOrGearCultivationRequest): unknown {
    const obj: any = {};
    if (message.CultivationTableID !== 0) {
      obj.CultivationTableID = Math.round(message.CultivationTableID);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LearnOrGearCultivationRequest>, I>>(base?: I): LearnOrGearCultivationRequest {
    return LearnOrGearCultivationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LearnOrGearCultivationRequest>, I>>(
    object: I,
  ): LearnOrGearCultivationRequest {
    const message = createBaseLearnOrGearCultivationRequest();
    message.CultivationTableID = object.CultivationTableID ?? 0;
    return message;
  },
};

function createBaseLearnOrGearCultivationResponse(): LearnOrGearCultivationResponse {
  return { info: undefined };
}

export const LearnOrGearCultivationResponse: MessageFns<LearnOrGearCultivationResponse> = {
  encode(message: LearnOrGearCultivationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      CultivationInfo.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LearnOrGearCultivationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLearnOrGearCultivationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = CultivationInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LearnOrGearCultivationResponse {
    return { info: isSet(object.info) ? CultivationInfo.fromJSON(object.info) : undefined };
  },

  toJSON(message: LearnOrGearCultivationResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = CultivationInfo.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LearnOrGearCultivationResponse>, I>>(base?: I): LearnOrGearCultivationResponse {
    return LearnOrGearCultivationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LearnOrGearCultivationResponse>, I>>(
    object: I,
  ): LearnOrGearCultivationResponse {
    const message = createBaseLearnOrGearCultivationResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? CultivationInfo.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseCreateCultivationRequest(): CreateCultivationRequest {
  return { CultivationID0: "", CultivationID1: "", Description: "" };
}

export const CreateCultivationRequest: MessageFns<CreateCultivationRequest> = {
  encode(message: CreateCultivationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.CultivationID0 !== "") {
      writer.uint32(10).string(message.CultivationID0);
    }
    if (message.CultivationID1 !== "") {
      writer.uint32(18).string(message.CultivationID1);
    }
    if (message.Description !== "") {
      writer.uint32(26).string(message.Description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCultivationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCultivationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.CultivationID0 = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.CultivationID1 = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.Description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCultivationRequest {
    return {
      CultivationID0: isSet(object.CultivationID0) ? globalThis.String(object.CultivationID0) : "",
      CultivationID1: isSet(object.CultivationID1) ? globalThis.String(object.CultivationID1) : "",
      Description: isSet(object.Description) ? globalThis.String(object.Description) : "",
    };
  },

  toJSON(message: CreateCultivationRequest): unknown {
    const obj: any = {};
    if (message.CultivationID0 !== "") {
      obj.CultivationID0 = message.CultivationID0;
    }
    if (message.CultivationID1 !== "") {
      obj.CultivationID1 = message.CultivationID1;
    }
    if (message.Description !== "") {
      obj.Description = message.Description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCultivationRequest>, I>>(base?: I): CreateCultivationRequest {
    return CreateCultivationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCultivationRequest>, I>>(object: I): CreateCultivationRequest {
    const message = createBaseCreateCultivationRequest();
    message.CultivationID0 = object.CultivationID0 ?? "";
    message.CultivationID1 = object.CultivationID1 ?? "";
    message.Description = object.Description ?? "";
    return message;
  },
};

function createBaseCreateCultivationResponse(): CreateCultivationResponse {
  return { CultivationID: "", CultivationTableID: 0, Attributes: {}, IsNeedSelect: false, Skills: [] };
}

export const CreateCultivationResponse: MessageFns<CreateCultivationResponse> = {
  encode(message: CreateCultivationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.CultivationID !== "") {
      writer.uint32(10).string(message.CultivationID);
    }
    if (message.CultivationTableID !== 0) {
      writer.uint32(16).uint32(message.CultivationTableID);
    }
    globalThis.Object.entries(message.Attributes).forEach(([key, value]: [string, number]) => {
      CreateCultivationResponse_AttributesEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    if (message.IsNeedSelect !== false) {
      writer.uint32(32).bool(message.IsNeedSelect);
    }
    for (const v of message.Skills) {
      CultivationSkill.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCultivationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCultivationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.CultivationID = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.CultivationTableID = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = CreateCultivationResponse_AttributesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.Attributes[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.IsNeedSelect = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.Skills.push(CultivationSkill.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCultivationResponse {
    return {
      CultivationID: isSet(object.CultivationID) ? globalThis.String(object.CultivationID) : "",
      CultivationTableID: isSet(object.CultivationTableID) ? globalThis.Number(object.CultivationTableID) : 0,
      Attributes: isObject(object.Attributes)
        ? (globalThis.Object.entries(object.Attributes) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      IsNeedSelect: isSet(object.IsNeedSelect) ? globalThis.Boolean(object.IsNeedSelect) : false,
      Skills: globalThis.Array.isArray(object?.Skills)
        ? object.Skills.map((e: any) => CultivationSkill.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CreateCultivationResponse): unknown {
    const obj: any = {};
    if (message.CultivationID !== "") {
      obj.CultivationID = message.CultivationID;
    }
    if (message.CultivationTableID !== 0) {
      obj.CultivationTableID = Math.round(message.CultivationTableID);
    }
    if (message.Attributes) {
      const entries = globalThis.Object.entries(message.Attributes) as [string, number][];
      if (entries.length > 0) {
        obj.Attributes = {};
        entries.forEach(([k, v]) => {
          obj.Attributes[k] = Math.round(v);
        });
      }
    }
    if (message.IsNeedSelect !== false) {
      obj.IsNeedSelect = message.IsNeedSelect;
    }
    if (message.Skills?.length) {
      obj.Skills = message.Skills.map((e) => CultivationSkill.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCultivationResponse>, I>>(base?: I): CreateCultivationResponse {
    return CreateCultivationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCultivationResponse>, I>>(object: I): CreateCultivationResponse {
    const message = createBaseCreateCultivationResponse();
    message.CultivationID = object.CultivationID ?? "";
    message.CultivationTableID = object.CultivationTableID ?? 0;
    message.Attributes = (globalThis.Object.entries(object.Attributes ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.IsNeedSelect = object.IsNeedSelect ?? false;
    message.Skills = object.Skills?.map((e) => CultivationSkill.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateCultivationResponse_AttributesEntry(): CreateCultivationResponse_AttributesEntry {
  return { key: "", value: 0 };
}

export const CreateCultivationResponse_AttributesEntry: MessageFns<CreateCultivationResponse_AttributesEntry> = {
  encode(message: CreateCultivationResponse_AttributesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCultivationResponse_AttributesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCultivationResponse_AttributesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCultivationResponse_AttributesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: CreateCultivationResponse_AttributesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCultivationResponse_AttributesEntry>, I>>(
    base?: I,
  ): CreateCultivationResponse_AttributesEntry {
    return CreateCultivationResponse_AttributesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCultivationResponse_AttributesEntry>, I>>(
    object: I,
  ): CreateCultivationResponse_AttributesEntry {
    const message = createBaseCreateCultivationResponse_AttributesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseSelectCultivationRequest(): SelectCultivationRequest {
  return { CultivationID: "", Skills: undefined };
}

export const SelectCultivationRequest: MessageFns<SelectCultivationRequest> = {
  encode(message: SelectCultivationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.CultivationID !== "") {
      writer.uint32(10).string(message.CultivationID);
    }
    if (message.Skills !== undefined) {
      CultivationSkill.encode(message.Skills, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SelectCultivationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSelectCultivationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.CultivationID = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.Skills = CultivationSkill.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SelectCultivationRequest {
    return {
      CultivationID: isSet(object.CultivationID) ? globalThis.String(object.CultivationID) : "",
      Skills: isSet(object.Skills) ? CultivationSkill.fromJSON(object.Skills) : undefined,
    };
  },

  toJSON(message: SelectCultivationRequest): unknown {
    const obj: any = {};
    if (message.CultivationID !== "") {
      obj.CultivationID = message.CultivationID;
    }
    if (message.Skills !== undefined) {
      obj.Skills = CultivationSkill.toJSON(message.Skills);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SelectCultivationRequest>, I>>(base?: I): SelectCultivationRequest {
    return SelectCultivationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SelectCultivationRequest>, I>>(object: I): SelectCultivationRequest {
    const message = createBaseSelectCultivationRequest();
    message.CultivationID = object.CultivationID ?? "";
    message.Skills = (object.Skills !== undefined && object.Skills !== null)
      ? CultivationSkill.fromPartial(object.Skills)
      : undefined;
    return message;
  },
};

function createBaseSelectCultivationResponse(): SelectCultivationResponse {
  return { info: undefined };
}

export const SelectCultivationResponse: MessageFns<SelectCultivationResponse> = {
  encode(message: SelectCultivationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      CultivationInfo.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SelectCultivationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSelectCultivationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = CultivationInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SelectCultivationResponse {
    return { info: isSet(object.info) ? CultivationInfo.fromJSON(object.info) : undefined };
  },

  toJSON(message: SelectCultivationResponse): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = CultivationInfo.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SelectCultivationResponse>, I>>(base?: I): SelectCultivationResponse {
    return SelectCultivationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SelectCultivationResponse>, I>>(object: I): SelectCultivationResponse {
    const message = createBaseSelectCultivationResponse();
    message.info = (object.info !== undefined && object.info !== null)
      ? CultivationInfo.fromPartial(object.info)
      : undefined;
    return message;
  },
};

function createBaseFusionBBRequest(): FusionBBRequest {
  return { BB0: "", BB1: "" };
}

export const FusionBBRequest: MessageFns<FusionBBRequest> = {
  encode(message: FusionBBRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.BB0 !== "") {
      writer.uint32(10).string(message.BB0);
    }
    if (message.BB1 !== "") {
      writer.uint32(18).string(message.BB1);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FusionBBRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFusionBBRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.BB0 = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.BB1 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FusionBBRequest {
    return {
      BB0: isSet(object.BB0) ? globalThis.String(object.BB0) : "",
      BB1: isSet(object.BB1) ? globalThis.String(object.BB1) : "",
    };
  },

  toJSON(message: FusionBBRequest): unknown {
    const obj: any = {};
    if (message.BB0 !== "") {
      obj.BB0 = message.BB0;
    }
    if (message.BB1 !== "") {
      obj.BB1 = message.BB1;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FusionBBRequest>, I>>(base?: I): FusionBBRequest {
    return FusionBBRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FusionBBRequest>, I>>(object: I): FusionBBRequest {
    const message = createBaseFusionBBRequest();
    message.BB0 = object.BB0 ?? "";
    message.BB1 = object.BB1 ?? "";
    return message;
  },
};

function createBaseFusionBBRespone(): FusionBBRespone {
  return { NewBB: undefined };
}

export const FusionBBRespone: MessageFns<FusionBBRespone> = {
  encode(message: FusionBBRespone, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.NewBB !== undefined) {
      BBInfo.encode(message.NewBB, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FusionBBRespone {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFusionBBRespone();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.NewBB = BBInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FusionBBRespone {
    return { NewBB: isSet(object.NewBB) ? BBInfo.fromJSON(object.NewBB) : undefined };
  },

  toJSON(message: FusionBBRespone): unknown {
    const obj: any = {};
    if (message.NewBB !== undefined) {
      obj.NewBB = BBInfo.toJSON(message.NewBB);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FusionBBRespone>, I>>(base?: I): FusionBBRespone {
    return FusionBBRespone.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FusionBBRespone>, I>>(object: I): FusionBBRespone {
    const message = createBaseFusionBBRespone();
    message.NewBB = (object.NewBB !== undefined && object.NewBB !== null)
      ? BBInfo.fromPartial(object.NewBB)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
